# -*- coding: utf-8 -*-
"""Time.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4Y2tSDWib0SV7S03T-hGvkV_egJzvoe
"""

from datetime import datetime

now_method = datetime.now()

currentTime = now_method.strftime("%H:%M:%S")
print("Current Time =", currentTime)